"use client";
import { useEffect, useState } from "react";
import { createClient } from "@supabase/supabase-js";
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
export default function AuthPage({mode}:{mode:"login"|"signup"|"reset"}){const [client]=useState(()=>url&&anon?createClient(url,anon):null);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");const [recovery,setRecovery]=useState(false);
 useEffect(()=>{if(!client)return;const {data}=client.auth.onAuthStateChange((event,session)=>{if(event==="PASSWORD_RECOVERY"){setRecovery(true);return;}if(session&&mode==="login")window.location.replace("/dashboard");});return()=>data.subscription.unsubscribe();},[client,mode]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!client)return;setBusy(true);setError("");setMessage("");try{if(mode==="signup"){const {data,error}=await client.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/login`}});if(error)throw error;if(data.session)window.location.assign("/dashboard");else setMessage("Check your email for the verification link. After you confirm your address, sign in here.");}else if(mode==="login"){const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;}else if(recovery){if(password.length<8)throw Error("Use a password with at least 8 characters.");if(password!==confirm)throw Error("The passwords do not match.");const {error}=await client.auth.updateUser({password});if(error)throw error;setMessage("Your password has been changed. You can sign in now.");setPassword("");setConfirm("");setRecovery(false);await client.auth.signOut();}else{const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset-password`});if(error)throw error;setMessage("If the address belongs to an account, a password reset link will arrive by email.");}}catch(e){setError(e instanceof Error?e.message:"Could not complete that request.");}finally{setBusy(false);}}
 const title=mode==="signup"?"Create your studio account":mode==="reset"?(recovery?"Choose a new password":"Reset your password"):"Sign in to your studio";
 return <main className="auth-shell"><a className="auth-brand" href="/">The Photo Gallery <span>Studio workspace</span></a><section className="panel auth-card"><span className="eyebrow">THE PHOTO GALLERY</span><h1>{title}</h1><p>{mode==="signup"?"Start with a studio account. You can set up your workspace after signing in.":mode==="reset"?"We’ll send a secure reset link to your account email.":"Manage projects, private client galleries, invoices and media."}</p>{!url||!anon?<div className="auth-alert">Set <code>NEXT_PUBLIC_SUPABASE_URL</code> and <code>NEXT_PUBLIC_SUPABASE_ANON_KEY</code> in <code>apps/web/.env.local</code> before using authentication.</div>:<form className="auth-form" onSubmit={submit}>{(mode!=="reset"||!recovery)&&<label>Email address<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{(mode!=="reset"||recovery)&&<label>{recovery?"New password":"Password"}<input type="password" minLength={8} required autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{recovery&&<label>Confirm new password<input type="password" minLength={8} required autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}{error&&<div className="auth-alert auth-error" role="alert">{error}</div>}{message&&<div className="auth-alert auth-success" role="status">{message}</div>}<button className="primary" disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create account":mode==="reset"?(recovery?"Update password":"Send reset link"):"Sign in"}</button></form>}{mode==="login"&&<a className="auth-sub-link" href="/reset-password">Forgot your password?</a>}<div className="auth-footer">{mode==="login"?<>New to the platform? <a href="/signup">Create an account</a></>:<>Already have an account? <a href="/login">Sign in</a></>}</div><a className="auth-home" href="/dashboard">← Back to workspace</a></section></main>;
}
