"use client";
import { useEffect, useState } from "react";
import { createClient, type Session } from "@supabase/supabase-js";
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4100/api";
const supabase=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;
type Studio={id:string;name:string};type Project={id:string;name:string};type Media={id:string;filename:string;mime_type:string;file_size_bytes:number};type Link={title:string;customerLink:string;deliveryNote:string};
export default function GalleryDesk(){
 const [session,setSession]=useState<Session|null>(null);const [studios,setStudios]=useState<Studio[]>([]);const [org,setOrg]=useState("");const [projects,setProjects]=useState<Project[]>([]);const [project,setProject]=useState("");const [media,setMedia]=useState<Media[]>([]);const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [links,setLinks]=useState<Link[]>([]);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>setSession(data.session));const sub=supabase?.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub?.data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!session)return;fetch(`${api}/studios`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()).then(d=>{setStudios(d.studios||[]);if(d.studios?.length===1)setOrg(d.studios[0].id);}).catch(()=>setError("Could not load your studios."));},[session]);
 useEffect(()=>{if(!session||!org)return;fetch(`${api}/projects`,{headers:{Authorization:`Bearer ${session.access_token}`,"x-organization-id":org}}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);setProjects(d.projects||[]);}).catch(e=>setError(e.message));},[session,org]);
 useEffect(()=>{if(!session||!org||!project)return;fetch(`${api}/gallery-assets/${project}`,{headers:{Authorization:`Bearer ${session.access_token}`,"x-organization-id":org}}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);setMedia(d.media||[]);}).catch(e=>setError(e.message));},[session,org,project]);
 async function signIn(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);}
 async function create(e:React.FormEvent){e.preventDefault();if(!session||!org||!project)return;setBusy(true);setError("");try{const headers={Authorization:`Bearer ${session.access_token}`,"x-organization-id":org,"Content-Type":"application/json"};const created=await fetch(`${api}/galleries`,{method:"POST",headers,body:JSON.stringify({projectId:project,title,description})});const result=await created.json();if(!created.ok)throw Error(result.error||"Could not create the gallery.");let deliveryNote="Gallery created. Add a client email to send a registration invitation.";if(selected.length){const attached=await fetch(`${api}/galleries/${result.gallery.id}/attach`,{method:"POST",headers,body:JSON.stringify({mediaIds:selected})});const attachedResult=await attached.json();if(!attached.ok)throw Error(attachedResult.error||"Gallery created, but selected media could not be attached.");}
 const token=String(result.customerLink).split("/").pop()||"";const invitation=await fetch(`${api}/projects/${project}/customer-invitation`,{method:"POST",headers,body:JSON.stringify({galleryId:result.gallery.id,galleryToken:token})});const invitationResult=await invitation.json();if(invitation.ok)deliveryNote=`Registration invitation sent to ${invitationResult.email}.`;else deliveryNote=invitationResult.error||deliveryNote;
 const fullLink=`${location.origin}${result.customerLink}`;setLinks(v=>[{title,customerLink:fullLink,deliveryNote},...v]);await navigator.clipboard?.writeText(fullLink).catch(()=>{});setTitle("");setDescription("");setSelected([]);setMedia(v=>v.filter(m=>!selected.includes(m.id)));
 }catch(e){setError(e instanceof Error?e.message:"Could not prepare the gallery.");}finally{setBusy(false);}}
 return <section className="panel gallery-desk">{!session?<><div><h2>Prepare a private gallery</h2><p>Sign in to share selected project media with your customer.</p></div><form className="connect-form" onSubmit={signIn}><input type="email" required placeholder="Studio email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary">Sign in</button></form>{error&&<p className="connect-error">{error}</p>}</>:<><div><h2>Create a private client gallery</h2><p>Customers receive a registration email with access to this private gallery. Downloads stay locked until the project balance is paid.</p></div><form className="quotation-form" onSubmit={create}><label>Studio<select required value={org} onChange={e=>setOrg(e.target.value)}><option value="">Select studio</option>{studios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Project<select required value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Gallery title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Wedding highlights"/></label><label>Note for your customer<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="A note to introduce the gallery"/></label>{media.length>0&&<div className="asset-picker"><b>Choose ready media for this gallery</b>{media.map(m=><label key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}/><span>{m.mime_type.startsWith("video/")?"▶":"▧"}</span>{m.filename}</label>)}</div>}{error&&<p className="connect-error">{error}</p>}<button className="primary" disabled={!org||!project||busy}>{busy?"Preparing gallery…":"Create gallery and invite customer"}</button></form>{links.map((l,i)=><div className="notice" key={`${l.customerLink}-${i}`}><b>{l.title}</b><p>{l.deliveryNote}</p><a href={l.customerLink} target="_blank" rel="noreferrer">Open customer gallery →</a><input readOnly value={l.customerLink} onFocus={e=>e.currentTarget.select()}/></div>)}</>}</section>
}
