"use client";
import { useEffect, useState } from "react";
import { createClient, type Session } from "@supabase/supabase-js";
const api = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4100/api";
const supabase = process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ? createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) : null;
type Studio = { id:string; name:string; status:string; created_at:string; review_note:string; organization_members:{user_id:string;role:string}[] };
type Organization = { id:string; name:string; status:string; created_at:string; storage_limit_bytes:number; storage_used_bytes:number; storage_reserved_bytes:number };
type Overview={summary:{studios:number;customers:number;projects:number;payments:number;capturedPayments:number};projects:any[];customers:any[];payments:any[];subscriptions:any[];health:{api:string;database:string}};
function bytes(n:number){if(n<1024**3)return `${(n/1024**2).toFixed(0)} MB`;if(n<1024**4)return `${(n/1024**3).toFixed(1)} GB`;return `${(n/1024**4).toFixed(2)} TB`;}
function money(n:number){return `₹${(Number(n||0)/100).toLocaleString("en-IN")}`;}
export default function AdminPage(){
 const [session,setSession]=useState<Session|null>(null);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [studios,setStudios]=useState<Studio[]>([]);const [organizations,setOrganizations]=useState<Organization[]>([]);const [overview,setOverview]=useState<Overview|null>(null);const [limits,setLimits]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [busy,setBusy]=useState("");
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>setSession(data.session));const sub=supabase?.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub?.data.subscription.unsubscribe();},[]);
 async function load(){if(!session)return;setLoading(true);setError("");try{const h={Authorization:`Bearer ${session.access_token}`};const [a,b,c]=await Promise.all([fetch(`${api}/admin/studios`,{headers:h}),fetch(`${api}/admin/organizations`,{headers:h}),fetch(`${api}/admin/overview`,{headers:h})]);const ad=await a.json(),bd=await b.json(),cd=await c.json();if(!a.ok)throw Error(ad.error||"Could not load studio approvals.");if(!b.ok)throw Error(bd.error||"Could not load studio operations.");if(!c.ok)throw Error(cd.error||"Could not load the platform overview.");setStudios(ad.studios||[]);setOrganizations(bd.organizations||[]);setOverview(cd);setLimits(Object.fromEntries((bd.organizations||[]).map((o:Organization)=>[o.id,String(Math.floor(o.storage_limit_bytes/1024**3))])));}catch(e){setError(e instanceof Error?e.message:"Could not load admin data.");}finally{setLoading(false);}}
 useEffect(()=>{if(session)void load();},[session]);
 async function signIn(e:React.FormEvent){e.preventDefault();if(!supabase){setError("Supabase configuration is required.");return;}const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);}
 async function decision(id:string,decision:"APPROVE"|"REJECT"){setError("");const r=await fetch(`${api}/admin/studios/${id}/decision`,{method:"POST",headers:{Authorization:`Bearer ${session?.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({decision})});const d=await r.json();if(!r.ok){setError(d.error);return;}setMessage(`${d.studio.name} ${decision==="APPROVE"?"approved":"declined"}.`);await load();}
 async function updateStudio(o:Organization,patch:{storageLimitBytes?:number;status?:string}){if(!session)return;setBusy(o.id);setError("");try{const r=await fetch(`${api}/admin/organizations/${o.id}`,{method:"PATCH",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(patch)});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not update studio.");setMessage(`${o.name} updated.`);await load();}catch(e){setError(e instanceof Error?e.message:"Could not update studio.");}finally{setBusy("");}}
 return <main className="admin-page"><header className="public-header"><a href="/" className="brand"><span className="brand-mark">f</span><span>frame<span className="brand-light">folk</span><small>PLATFORM ADMIN</small></span></a><a className="text-button" href="/dashboard">Studio workspace →</a></header><div className="admin-content"><p className="eyebrow">PLATFORM OPERATIONS</p><h1>Studio administration</h1><p className="subhead">Monitor platform activity, review studio registrations, and manage storage accounts.</p>{error&&<div className="public-error">{error}</div>}{message&&<div className="notice">{message}</div>}{!session?<section className="panel admin-login"><h2>Administrator sign in</h2><form className="request-form" onSubmit={signIn}><input type="email" required placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary">Sign in</button></form><small>Only users provisioned in the platform_admins table can use these controls.</small></section>:<>
 <section className="admin-overview"><div className="panel-head"><div><h2>Platform overview</h2><p>Current account, workflow, billing and service health at a glance.</p></div><span className="status status-green"><i/>{overview?.health.api||"Checking"} · API</span></div>{loading&&!overview?<div className="panel public-empty">Loading platform activity…</div>:overview&&<><div className="admin-stat-grid">{[["STUDIOS",overview.summary.studios],["CUSTOMERS",overview.summary.customers],["PROJECTS",overview.summary.projects],["PAYMENTS",overview.summary.payments],["CAPTURED",overview.summary.capturedPayments]].map(([label,value])=><article className="panel admin-stat" key={label}><small>{label}</small><b>{value}</b></article>)}</div><div className="admin-health"><span><i/>API service · {overview.health.api}</span><span><i/>Database queries · {overview.health.database}</span><button className="text-button" onClick={()=>void load()}>Refresh platform data</button></div><div className="admin-data-grid"><section className="panel admin-data-card"><h3>Recent projects</h3>{overview.projects.length?overview.projects.map(p=><div className="admin-data-row" key={p.id}><span><b>{p.name}</b><small>{p.organizations?.name||"Studio"} · {p.clients?.name||"Client"}</small></span><span>{p.status.replaceAll("_"," ")}<small>{money(p.amount_paid)} / {money(p.total_amount)} paid</small></span></div>):<p>No projects yet.</p>}</section><section className="panel admin-data-card"><h3>Recent customers</h3>{overview.customers.length?overview.customers.map(c=><div className="admin-data-row" key={c.id}><span><b>{c.name}</b><small>{c.email||"No email"}</small></span><span>{c.organizations?.name||"Studio"}<small>{new Date(c.created_at).toLocaleDateString()}</small></span></div>):<p>No customer records yet.</p>}</section><section className="panel admin-data-card"><h3>Recent payments</h3>{overview.payments.length?overview.payments.map(p=><div className="admin-data-row" key={p.id}><span><b>{money(p.amount)} {p.currency}</b><small>{p.projects?.name||"Project"} · {p.organizations?.name||"Studio"}</small></span><span className={`status ${p.status==="CAPTURED"?"status-green":p.status==="FAILED"?"status-amber":"status-blue"}`}><i/>{p.status.replaceAll("_"," ")}</span></div>):<p>No payment attempts yet.</p>}</section><section className="panel admin-data-card"><h3>Subscriptions</h3>{overview.subscriptions.length?overview.subscriptions.map(s=><div className="admin-data-row" key={s.organization_id}><span><b>{s.organizations?.name||"Studio"}</b><small>Plan account</small></span><span>{s.status.replaceAll("_"," ")}<small>{s.current_period_end?new Date(s.current_period_end).toLocaleDateString():"No end date set"}</small></span></div>):<p>No subscription records yet.</p>}</section></div></>}</section>
 <section className="admin-section"><div className="panel-head"><div><h2>Studio approvals</h2><p>Review new studio registrations before they can publish.</p></div></div>{studios.length===0?<div className="panel public-empty">No studios are waiting for review.</div>:<div className="admin-list">{studios.map(s=><article className="panel review-card" key={s.id}><div><span className="status status-amber"><i/>Pending review</span><h2>{s.name}</h2><p>Submitted {new Date(s.created_at).toLocaleDateString()} · {s.organization_members?.length||0} member(s)</p>{s.review_note&&<p>{s.review_note}</p>}</div><div className="review-actions"><button className="secondary-button" onClick={()=>void decision(s.id,"REJECT")}>Decline</button><button className="primary" onClick={()=>void decision(s.id,"APPROVE")}>Approve studio</button></div></article>)}</div>}</section>
 <section className="admin-operations"><div className="panel-head"><div><h2>Studio accounts and storage</h2><p>Storage values are in GiB. Lowering a limit below current usage blocks new uploads until usage falls.</p></div></div>{organizations.length===0?<div className="panel public-empty">No studio accounts found.</div>:<div className="admin-list">{organizations.map(o=>{const used=o.storage_used_bytes+o.storage_reserved_bytes;const pct=o.storage_limit_bytes?Math.min(100,used/o.storage_limit_bytes*100):0;return <article className="panel admin-org-card" key={o.id}><div className="admin-org-head"><div><span className={`status ${o.status==="ACTIVE"?"status-green":o.status==="SUSPENDED"?"status-amber":"status-blue"}`}><i/>{o.status.replaceAll("_"," ")}</span><h2>{o.name}</h2><small>Created {new Date(o.created_at).toLocaleDateString()}</small></div><button className={o.status==="ACTIVE"?"secondary-button":"primary"} disabled={busy===o.id||o.status==="PENDING_APPROVAL"} onClick={()=>void updateStudio(o,{status:o.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})}>{o.status==="ACTIVE"?"Suspend studio":"Activate studio"}</button></div><div className="storage-meter"><i style={{width:`${pct}%`}}/></div><p>{bytes(used)} used of {bytes(o.storage_limit_bytes)} · {pct.toFixed(0)}%</p><div className="admin-limit"><label>Storage limit (GiB)<input type="number" min="0" max="5242880" step="1" value={limits[o.id]??""} onChange={e=>setLimits(v=>({...v,[o.id]:e.target.value}))}/></label><button className="text-button" disabled={busy===o.id||limits[o.id]==null||!Number.isFinite(Number(limits[o.id]))||Number(limits[o.id])<0} onClick={()=>void updateStudio(o,{storageLimitBytes:Math.round(Number(limits[o.id])*1024**3)})}>{busy===o.id?"Saving…":"Save limit"}</button></div></article>})}</div>}</section></>}</div></main>
}
